### PR TITLE
fix: Fix Podman link to the correct link

### LINKED ISSUE #523: [Bug] wrong Podmaninstallation link
### What version of WinBoat are you running?

0.9.0

### Your Environment

CachyOS

### Steps to Reproduce / Context

When switching from Docker to Podman in the setup, the hyperlink `How?` keeps pointing to the Docker docs.

Image

### Logs

no logs

### Expected Behavior

A link to the Podman docs should be provided.

### Current Behavior

You will be directed to the Docker docs.

### Possible Solution

_No response_

### Quality Notice

- [x] I have checked the issue tracker and verified that this bug is a unique case.

### LINKED ISSUE #760: [Bug] "How?" button links to Docker documentation instead of Podman in onboarding flow
### What version of WinBoat are you running?

0.9.0

### Your Environment

Archlinux

### Steps to Reproduce / Context

There's a bug here: When I switch from the Docker tab to the Podman tab and click 'How?', the documentation that opens is still the Docker installation guide instead of the Podman installation guide.
Image

### Logs

none

### Expected Behavior

This should open poddman installation

### Current Behavior

This open docker installation

### Possible Solution

_No response_

### Quality Notice

- [x] I have checked the issue tracker and verified that this bug is a unique case.

### PR DESCRIPTION
**Pull request by LittleT6109**
Fixed the link for the Podman "How?" leading to Docker instead of Podman

Closes #523 
Closes #760

### CODE REVIEW

File: src/renderer/views/SetupUI.vue [hunk 1]
```diff
@@ -125,12 +125,13 @@
                                 </div>
                                 installed
                                 <a
-                                    href="https://docs.docker.com/engine/install/"
+                                    :href="containerRuntime === 'Podman'
```
Comment (waffles-dev) [inline src/renderer/views/SetupUI.vue]:
```suggestion
                                    :href="containerRuntime === ContainerRuntimes.PODMAN
```
